services:
    api_platform.rate_limiter.event.subscriber:
        public: true
        class: ApiPlatformRateLimiterBundle\EventSubscriber\RateLimiterSubscriber
        tags:
            - { name: kernel.event_subscriber }